[AloneMusicPlayer]

; Specifies the audio filepath within the game directory
File=modloader\Alone\audio\music.mp3

; Specifies whether the audio plays only once or loops continuously (0 = play once; 1 = loop continuously)
Loop=1

; Specifies the volume (0 to 127)
Volume=127

; Specifies whether the player can toggle the music on or off by pressing the M key (0 = toggle key disabled; 1 = toggle key enabled)
ToggleEnabled=1

; Specifies whether the audio stream starts in the menu or after game initialization (0 = audio starts in game; 1 = audio starts in menu)
StartInMenu=0

; Specifies whether the audio stream starts automatically or has to be toggled manually by the player (0 = audio starts automatically; 1 = audio stays paused until toggled)
StartPaused=0
